"""Build and send the refresh digest email (top standard props + moneylines)."""

from __future__ import annotations

import os
import re
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any

import json

_DATA = Path(__file__).resolve().parent.parent.parent / "data"

_DIGEST_SUBJECT = "NBA Prop Lab — daily props & moneylines"

_EMAIL_RE = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")


def is_valid_email(addr: str) -> bool:
    s = (addr or "").strip()
    return bool(s) and len(s) <= 255 and _EMAIL_RE.match(s) is not None


def _load_json_list(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        with path.open() as f:
            data = json.load(f)
        return data if isinstance(data, list) else []
    except (json.JSONDecodeError, OSError):
        return []


def top_props_by_confidence(n: int = 10) -> list[dict[str, Any]]:
    """Top N by confidence, PrizePicks **standard** lines only (excludes goblin/safer, demon)."""
    rows = _load_json_list(_DATA / "prizepicks_results.json")
    standard = [
        r
        for r in rows
        if (str(r.get("odds_type") or "standard")).lower() == "standard"
    ]
    standard.sort(
        key=lambda r: float(r.get("confidence") or 0),
        reverse=True,
    )
    return standard[:n]


def all_moneylines() -> list[dict[str, Any]]:
    return _load_json_list(_DATA / "moneylines.json")


def build_digest_plain(top_props: list[dict], moneylines: list[dict]) -> str:
    lines: list[str] = [
        "NBA Prop Lab — refresh digest",
        "",
        f"Top {len(top_props)} standard props (by confidence)",
        "-" * 40,
    ]
    for i, p in enumerate(top_props, 1):
        name = p.get("name", "?")
        label = p.get("label", p.get("stat", "?"))
        line = p.get("line", "?")
        conf = p.get("confidence", "?")
        team = p.get("team", "")
        lines.append(f"{i}. {name} ({team}) — {label} O {line} — conf {conf}")
    lines.extend(["", "Moneylines (all games)", "-" * 40])
    if not moneylines:
        lines.append("(none in moneylines.json)")
    else:
        for g in moneylines:
            away = g.get("away_team_name") or g.get("away", "?")
            home = g.get("home_team_name") or g.get("home", "?")
            pred = g.get("predicted_winner", "?")
            lines.append(f"{away} @ {home} — pick {pred}")
    return "\n".join(lines)


def build_digest_html(top_props: list[dict], moneylines: list[dict]) -> str:
    prop_rows = "".join(
        f"<tr><td>{i}</td><td>{_h(p.get('name'))}</td><td>{_h(p.get('team'))}</td>"
        f"<td>{_h(p.get('label', p.get('stat')))}</td><td>{_h(p.get('line'))}</td>"
        f"<td>{_h(p.get('confidence'))}</td></tr>"
        for i, p in enumerate(top_props, 1)
    )
    if not moneylines:
        ml_rows = "<tr><td colspan='3'>No moneylines in snapshot.</td></tr>"
    else:
        ml_rows = "".join(
            f"<tr><td>{_h(g.get('away_team_name') or g.get('away'))}</td>"
            f"<td>{_h(g.get('home_team_name') or g.get('home'))}</td>"
            f"<td>{_h(g.get('predicted_winner'))}</td></tr>"
            for g in moneylines
        )
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>NBA Prop Lab digest</title></head>
<body style="font-family:system-ui,sans-serif;line-height:1.5;color:#111">
<h2>NBA Prop Lab — refresh digest</h2>
<h3>Top {len(top_props)} standard props (confidence)</h3>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-size:14px">
<thead><tr><th>#</th><th>Player</th><th>Team</th><th>Stat</th><th>Line</th><th>Conf</th></tr></thead>
<tbody>{prop_rows}</tbody></table>
<h3>Moneylines</h3>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-size:14px">
<thead><tr><th>Away</th><th>Home</th><th>Pick</th></tr></thead>
<tbody>{ml_rows}</tbody></table>
<p style="color:#666;font-size:12px">Generated by your refresh pipeline.</p>
</body></html>"""


def _h(val: Any) -> str:
    if val is None:
        return "—"
    s = str(val)
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def smtp_missing_env_keys() -> list[str]:
    """Which of the required SMTP_* vars are unset or blank."""
    keys = ("SMTP_HOST", "SMTP_USER", "SMTP_PASSWORD")
    missing: list[str] = []
    for k in keys:
        if not (os.environ.get(k) or "").strip():
            missing.append(k)
    return missing


def smtp_configured() -> bool:
    return len(smtp_missing_env_keys()) == 0


def email_delivery_configured() -> bool:
    """True when SMTP_* env is complete enough to send."""
    return smtp_configured()


def send_digest_to_recipients(recipients: list[str]) -> None:
    if not recipients:
        return
    if not email_delivery_configured():
        raise RuntimeError(
            "Email not configured: set SMTP_HOST + SMTP_USER + SMTP_PASSWORD (see README)"
        )

    top = top_props_by_confidence(10)
    ml = all_moneylines()
    plain = build_digest_plain(top, ml)
    html = build_digest_html(top, ml)

    _send_digest_smtp(recipients, plain, html)


def _send_digest_smtp(recipients: list[str], plain: str, html: str) -> None:
    host = os.environ["SMTP_HOST"].strip()
    port = int(os.environ.get("SMTP_PORT", "587"))
    user = os.environ["SMTP_USER"].strip()
    password = os.environ["SMTP_PASSWORD"].strip()
    from_addr = os.environ.get("SMTP_FROM", user).strip()
    use_tls = os.environ.get("SMTP_USE_TLS", "1").strip().lower() not in (
        "0",
        "false",
        "no",
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = _DIGEST_SUBJECT
    msg["From"] = from_addr
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(plain, "plain", "utf-8"))
    msg.attach(MIMEText(html, "html", "utf-8"))

    with smtplib.SMTP(host, port, timeout=60) as server:
        if use_tls:
            server.starttls()
        server.login(user, password)
        server.sendmail(from_addr, recipients, msg.as_string())
